import './globals.css';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import NavBar from './components/NavBar';

const inter = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Issue Tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <main className="flex justify-center">{children}</main>
      </body>
    </html>
  );
}
